app/routes/admin.py
from flask import Blueprint, render_template, jsonify
from app.utils.auth_utils import privilege_required
from app.utils.db_utils import get_all_users, get_all_roles, get_all_privileges, get_role
from app.utils.session_validation import session_required

admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/manage_users')
@privilege_required('manage_users')
@session_required
def manage_users():
    users = get_all_users()
    return render_template('admin_panel/table_users.html', users=users)

@admin_bp.route('/manage_roles')
@privilege_required('manage_users')
@session_required
def manage_roles():
    roles = get_all_roles()
    all_privileges = get_all_privileges()
    return render_template('admin_panel/table_roles.html', roles=roles, all_privileges=all_privileges)

@admin_bp.route('/manage_privileges')
@privilege_required('manage_users')
@session_required
def manage_privileges():
    privileges = get_all_privileges()
    return render_template('admin_panel/table_privileges.html', privileges=privileges)

@admin_bp.route('/')
@privilege_required('manage_users')
@session_required
def admin_panel():
    return render_template('admin_panel/admin_panel.html')

@admin_bp.route('/roles/<int:role_id>', methods=['GET'])
def get_role_details(role_id):
    role = get_role(role_id)
    return jsonify(role)

app/routes/auth.py
from flask import Blueprint, jsonify, request, redirect, url_for, flash, session as flask_session
from flask import render_template
from flask_cors import cross_origin
from app.models.erp_models import User
from app.utils.session_utils import create_session, validate_session, delete_session
from app import db
from app.config import Config

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/authenticate', methods=['GET', 'POST'])
@cross_origin(supports_credentials=True)
def authenticate():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            # Create a new session
            session_key = create_session(user.id, Config.SESSION_EXPIRATION_MINUTES)
            flask_session['session_key'] = session_key
            flask_session['user_id'] = user.id
            flash('Login successful!', 'success')
            print("Login Attempt Successful")

            return redirect(url_for('main.operational_main', _external=True))
        else:
            flash('Invalid username or password', 'danger')
            print("Login Attempt Failed")

            return redirect(url_for('auth.login'))


@auth_bp.route('/logout')
@cross_origin(supports_credentials=True)
def logout():
    session_key = flask_session.get('session_key')
    if session_key:
        delete_session(session_key)
    flask_session.clear()
    flash('You have been logged out.', 'success')
    return redirect(url_for('auth.login'))

@auth_bp.route('/logout_button')
@cross_origin(supports_credentials=True)
def logout_button():
    return redirect(url_for('auth.logout'))

@auth_bp.route('/login')
@cross_origin(supports_credentials=True)
def login():
    return render_template('login_page.html')

@auth_bp.route('/get_user_info')
@cross_origin(supports_credentials=True)
def get_user_info():
    user_id = flask_session.get('user_id')
    if user_id:
        user = User.query.get(user_id)
        if user:
            print(user.role.to_dict())
            return jsonify({
                'username': user.username,
                'role': user.role.to_dict()
            })
    return {'error': 'User not found'}, 404 

app/routes/main.py
import os
from flask import Blueprint, render_template, send_from_directory
from flask_cors import cross_origin
from app.utils.session_validation import session_required
from app.utils.auth_utils import privilege_required

main_bp = Blueprint('main', __name__)

@main_bp.route('/dashboard')
@privilege_required('view_reports')
@session_required
def dashboard():
    return render_template('dashboard.html')

@main_bp.route('/inventory/input')
@privilege_required('view_reports')
@session_required 
def stock_input():
    return render_template('inputbarang.html')

@main_bp.route('/inventory/history')
@privilege_required('view_reports')
@session_required
def stock_history():
    return render_template('historybarang.html')

@main_bp.route('/operational')
@session_required
def operational_main():
    return render_template('pos.html')

@main_bp.route('/purchase')
@session_required
def purchase_main():
    return render_template('purchase.html')

@main_bp.route('/sale')
@session_required
def sale_main():
    return render_template('pos.html')

@main_bp.route('/sale_report')
@privilege_required('view_reports')
@session_required
def sale_report():
    return render_template('sale_report.html')

@main_bp.route('/modul_panduan')
@session_required
def modul_panduan():
    pdf_path = os.path.join('static', 'media', 'pdf')
    return send_from_directory(pdf_path, 'Modul Panduan SIstem ERP Toko Gemilang (2).pdf')

app/templates/shared/navbar.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Add your right navbar links here -->
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout_button') }}">Logout</a>
        </li>
    </ul>
</nav>

app/templates/shared/sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{{ url_for('static', filename='media/img/logo_transparant.png') }}" alt="Logo Gemilang 888" class="brand-image">            <span class="brand-text font-weight-light"><b>SETG</b></span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- User Panel -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="#" id="username_sidebar" class="d-block">
                    <span id="sidebar_username"></span><br>
                    <small id="sidebar_userrole"></small>
                </a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2" data-widget="treeview" role="menu" data-accordian="false">
            <ul class="nav nav-pills nav-sidebar flex-column" role="menu">
                <li class="nav-item">
                    <a href="/main/dashboard" class="nav-link active">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Stock Barang
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class ="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ url_for('main.purchase_main') }}" class="nav-link">
                                <i class = "fas fa-plus nav-icon"></i>
                                <p>Input Stok</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('main.stock_history') }}" class="nav-link">
                                <i class = "fas fa-history nav-icon"></i>
                                <p>History Transaksi</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('inventory.index') }}" class="nav-link">
                                <i class = "fas fa-warehouse nav-icon"></i>
                                <p>Inventory</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('main.operational_main') }}" class="nav-link">
                        <i class="nav-icon fas fa-cash-register"></i>
                        <p>Operational</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('main.sale_report') }}" class="nav-link">
                        <i class="nav-icon fas fa-chart-line"></i>
                        <p>Laporan Penjualan</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('main.modul_panduan') }}" class="nav-link" target="_blank">
                        <i class="nav-icon fas fa-book"></i>
                        <p>Modul Panduan</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('admin.admin_panel') }}" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>Administration</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- /.sidebar -->
</aside>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        fetch('{{ url_for("auth.get_user_info") }}')
            .then(response => response.json())
            .then(data => {
                if (!data.error) {
                    document.getElementById('sidebar_username').textContent = data.username;
                    document.getElementById('sidebar_userrole').textContent = data.role.name;
                }
            });
    });
</script>